---

- name: create file
  hosts: webservers
  remote_user: mjd

  tasks:
    - name: create txt file
      shell: echo "This is a small text file." > ~/small.txt
    - name: append to the text file
      shell: echo "Another brick in the wall." >> ~/small.txt
    - name: date the file
      raw: date >> ~/small.txt
... 
